sonar.projectKey=school-management-system-api
sonar.projectName=School Management System API
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

sonar.exclusions=**/*.module.ts,**/main.ts,**/infrastructure/database/migrations/**,**/infrastructure/database/data-source.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
